//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateRepository.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skate
    {
        public string SkateboardType { get; set; }
        public string SkateboardName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int Rating { get; set; }
    }
}
